<?php

/**
 * Filament v2 ships its CSS pre-compiled with amber as the "primary" colour.
 * This script extracts every rule whose selector references `primary` and
 * rewrites the amber values to the LITUS Group navy palette, producing
 * public/css/admin-primary.css (loaded after Filament's own stylesheet).
 *
 * Re-run after upgrading Filament:  php scripts/build-admin-primary.php
 */

$source = __DIR__.'/../vendor/filament/filament/dist/app.css';
$target = __DIR__.'/../public/css/admin-primary.css';

// Tailwind amber (Filament default primary) => LITUS navy, as "r g b".
$palette = [
    '255 251 235' => '240 243 250', // 50
    '254 243 199' => '221 227 244', // 100
    '253 230 138' => '187 199 234', // 200
    '252 211 77' => '142 161 216',  // 300
    '251 191 36' => '84 110 196',   // 400
    '245 158 11' => '30 58 158',    // 500
    '217 119 6' => '20 45 135',     // 600
    '180 83 9' => '14 38 117',      // 700
    '146 64 14' => '11 30 92',      // 800
    '120 53 15' => '9 24 72',       // 900
];

// Also cover the comma-separated rgba() and hex spellings the minifier emits.
$hex = fn (string $rgb) => '#'.implode('', array_map(fn ($c) => str_pad(dechex((int) $c), 2, '0', STR_PAD_LEFT), explode(' ', $rgb)));
foreach ($palette as $from => $to) {
    $palette[str_replace(' ', ',', $from)] = str_replace(' ', ',', $to);
    $palette[$hex($from)] = $hex($to);
}

$css = file_get_contents($source);
$css = preg_replace('#/\*.*?\*/#s', '', $css);

$out = [];

// Walk top-level blocks, descending one level into @media / @supports.
$walk = function (string $css, ?string $wrapper) use (&$walk, &$out, $palette) {
    $len = strlen($css);
    $i = 0;
    while ($i < $len) {
        $open = strpos($css, '{', $i);
        if ($open === false) {
            break;
        }
        $selector = trim(substr($css, $i, $open - $i));
        $depth = 1;
        $j = $open + 1;
        while ($j < $len && $depth > 0) {
            $depth += $css[$j] === '{' ? 1 : ($css[$j] === '}' ? -1 : 0);
            $j++;
        }
        $body = substr($css, $open + 1, $j - $open - 2);
        $i = $j;

        if (str_starts_with($selector, '@media') || str_starts_with($selector, '@supports')) {
            $walk($body, $selector);
            continue;
        }
        if (str_starts_with($selector, '@') || ! str_contains($selector, 'primary')) {
            continue;
        }

        $new = strtr($body, $palette);
        if ($new === $body) {
            continue;
        }
        $rule = $selector.'{'.$new.'}';
        $out[] = $wrapper ? $wrapper.'{'.$rule.'}' : $rule;
    }
};

$walk($css, null);

file_put_contents(
    $target,
    "/* Generated by scripts/build-admin-primary.php — do not edit by hand. */\n".implode("\n", $out)."\n"
);

echo 'Wrote '.count($out).' rules to '.realpath($target).PHP_EOL;
